use_frameworks!

platform :ios, '10.0'

target 'QaHubIos_Example' do
  pod 'QaHubIos', :path => '../'
  pod 'Alamofire', '~> 5.9.0'

  target 'QaHubIos_Tests' do
    inherit! :search_paths

    
  end
end
